// SPDX-License-Identifier: BSL-1.1
// Copyright (c) 2026 MuVeraAI Corporation

// Package keys provides cryptographic key management for agent identities.
// The KeyManager interface is pluggable; two backends ship with this package:
// InMemoryKeyStore (ephemeral) and FileKeyStore (persistent, encrypted JSON).
//
// TEE and HSM backends are explicitly out of scope for this package.
package keys

import (
	"context"
	"crypto/ed25519"

	"github.com/aumos-ai/agent-identity-framework/types"
)

// KeyPair holds an Ed25519 public/private key pair and the metadata associated with it.
type KeyPair struct {
	// KeyID is a stable identifier for this key pair (typically a UUID).
	KeyID string `json:"keyId"`
	// Algorithm identifies the key algorithm; always Ed25519 for keys generated by this package.
	Algorithm types.KeyAlgorithm `json:"algorithm"`
	// PublicKey is the raw 32-byte Ed25519 public key.
	PublicKey ed25519.PublicKey `json:"publicKey"`
	// PrivateKey is the raw 64-byte Ed25519 private key. Never serialized to external systems.
	PrivateKey ed25519.PrivateKey `json:"-"`
	// OwnerDID optionally records which agent DID owns this key.
	OwnerDID string `json:"ownerDid,omitempty"`
}

// KeyManager is the interface that key storage backends must implement.
// All methods must be safe for concurrent use from multiple goroutines.
type KeyManager interface {
	// Generate creates a new Ed25519 key pair, stores it, and returns it.
	// The returned KeyPair includes the private key material.
	Generate(ctx context.Context) (*KeyPair, error)

	// Store persists an externally provided key pair.
	Store(ctx context.Context, kp *KeyPair) error

	// Load retrieves a key pair by its KeyID.
	// Returns ErrKeyNotFound if the key does not exist.
	Load(ctx context.Context, keyID string) (*KeyPair, error)

	// Rotate generates a new key pair to replace the one identified by oldKeyID.
	// The old key pair is preserved in the store for a grace period to allow
	// in-flight credential verification to continue.
	// Returns the new KeyPair and a rotation record.
	Rotate(ctx context.Context, oldKeyID string, reason types.KeyRotationReason) (*KeyPair, *types.KeyRotationRecord, error)

	// List returns all key IDs currently in the store.
	List(ctx context.Context) ([]string, error)
}
